/* ============================================================
   TECNOROSITA — data.js
   Base de datos unificada con sincronización de LocalStorage.
   ============================================================ */

const PRODUCTS_DEFAULT = [
  {
    id: 1,
    sku: "TRS-KB-APX7",
    name: "Teclado Mecánico Apex Pro 7 RGB",
    category: "Teclados",
    price: 139990,
    originalPrice: 179990,
    stock: 14,
    stockCritico: 3,
    icon: "keyboard",
    img: "https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=600&q=80",
    featured: true,
    rating: 4.8,
    shortDesc: "Switches mecánicos hot-swap, retroiluminación RGB por tecla y estructura en aluminio aeronáutico.",
    description: "El Apex Pro 7 redefine la precisión en escritura y juego. Cuenta con switches hot-swap personalizables, chasis de aluminio de grado aeronáutico y efectos lumínicos configurables por software."
  },
  {
    id: 2,
    sku: "TRS-MS-VIPER",
    name: "Mouse Gamer Inalámbrico Viper Elite X",
    category: "Mouse",
    price: 89990,
    originalPrice: 119990,
    stock: 22,
    stockCritico: 5,
    icon: "mouse",
    img: "https://images.unsplash.com/photo-1615663245857-ac1eeb536fcb?auto=format&fit=crop&w=600&q=80",
    featured: true,
    rating: 4.7,
    shortDesc: "Sensor óptico 32.000 DPI, 58 g de peso y hasta 90 horas de batería.",
    description: "Diseñado para eSports. Ultraligero con solo 58 gramos, sensor óptico de alta precisión y patines de teflón virgen para un deslizamiento sin fricción."
  },
  {
    id: 3,
    sku: "TRS-HS-AURA",
    name: "Audífonos Gamer Aura Surround 7.1",
    category: "Audífonos",
    price: 109990,
    originalPrice: 139990,
    stock: 18,
    stockCritico: 4,
    icon: "headset",
    img: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?auto=format&fit=crop&w=600&q=80",
    featured: true,
    rating: 4.9,
    shortDesc: "Sonido envolvente 5.1, micrófono con cancelación de ruido y aros dorados.",
    description: "Sumérgete en la batalla con los Aura Surround. Sonido posicional ultra nítido, almohadillas de espuma viscoelástica y micrófono con cancelación activa de ruido ambiental."
  },
  {
    id: 4,
    sku: "TRS-MN-240HZ",
    name: "Monitor Curvo Gamer 27\" QHD 240Hz",
    category: "Monitores",
    price: 499990,
    originalPrice: 589990,
    stock: 9,
    stockCritico: 2,
    icon: "monitor",
    img: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=600&q=80",
    featured: true,
    rating: 4.9,
    shortDesc: "Panel QHD 240Hz, 1ms de respuesta y compatibilidad G-Sync / FreeSync.",
    description: "Experimenta la máxima fluidez visual. Tasa de refresco de 240Hz y tiempo de respuesta de 1ms MPRT para eliminar el ghosting en partidas competitivas."
  },
  {
    id: 5,
    sku: "TRS-CH-TITAN",
    name: "Silla Ergonomica Gamer Titan Royal",
    category: "Sillas",
    price: 329990,
    originalPrice: 399990,
    stock: 7,
    stockCritico: 2,
    icon: "chair",
    img: "https://images.unsplash.com/photo-1598327105666-5b89351cb315?auto=format&fit=crop&w=600&q=80",
    featured: false,
    rating: 4.6,
    shortDesc: "Cuero premium, reclinación 165°, soporte lumbar 4D y base de aluminio.",
    description: "Confort extremo para maratones de juego o trabajo. Estructura de acero reforzado, pistón de gas clase 4 y tapizado en cuero sintético respirable de alta durabilidad."
  },
  {
    id: 6,
    sku: "TRS-LP-STRIX",
    name: "Notebook Gamer Eclipse Pro 16\"",
    category: "Laptops",
    price: 1299990,
    originalPrice: 1499990,
    stock: 5,
    stockCritico: 1,
    icon: "laptop",
    img: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=600&q=80",
    featured: true,
    rating: 4.9,
    shortDesc: "GPU RTX serie 40, pantalla 165Hz QHD y chasis de magnesio negro mate.",
    description: "Potencia de escritorio en formato portátil. Equipada con procesador de última generación y gráfica dedicada para jugar con Ray Tracing activado sin sacrificar fotogramas."
  },
  {
    id: 7,
    sku: "TRS-KB-MINI",
    name: "Teclado Compacto 60% Quantum",
    category: "Teclados",
    price: 79990,
    originalPrice: 99990,
    stock: 16,
    stockCritico: 4,
    icon: "keyboard",
    img: "https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=600&q=80",
    featured: false,
    rating: 4.5,
    shortDesc: "Formato 60% ultra portátil, conexión tri-modo y switches silenciosos.",
    description: "Optimiza el espacio de tu escritorio sin perder velocidad de respuesta. Conexión Bluetooth, 2.4GHz y cable USB-C desmontable."
  },
  {
    id: 8,
    sku: "TRS-MS-GOLD",
    name: "Mouse Edición Coleccionista Gold",
    category: "Mouse",
    price: 94990,
    originalPrice: 119990,
    stock: 11,
    stockCritico: 3,
    icon: "mouse",
    img: "https://images.unsplash.com/photo-1615663245857-ac1eeb536fcb?auto=format&fit=crop&w=600&q=80",
    featured: false,
    rating: 4.7,
    shortDesc: "Edición limitada con acabados dorados y sensor de 26.000 DPI.",
    description: "Diseño exclusivo con detalles bañados en tono dorado y rendimiento de nivel profesional para destacar en cualquier setup."
  },
  {
    id: 9,
    sku: "TRS-HS-WIRELESS",
    name: "Audífonos Inalámbricos Stealth Pro",
    category: "Audífonos",
    price: 129990,
    originalPrice: 159990,
    stock: 13,
    stockCritico: 3,
    icon: "headset",
    img: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?auto=format&fit=crop&w=600&q=80",
    featured: false,
    rating: 4.8,
    shortDesc: "Inalámbricos, 40 horas de batería y drivers planares de alta fidelidad.",
    description: "Libertad absoluta de movimiento y audio ultra definido para escuchar cada paso del enemigo."
  },
  {
    id: 10,
    sku: "TRS-MN-CURVED",
    name: "Monitor Ultrawide 34\" 165Hz",
    category: "Monitores",
    price: 649990,
    originalPrice: 749990,
    stock: 6,
    stockCritico: 2,
    icon: "monitor",
    img: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=600&q=80",
    featured: false,
    rating: 4.8,
    shortDesc: "Panel curvo 21:9, resolución UWQHD y 165Hz para inmersión total.",
    description: "Amplía tu campo de visión periférica con este monitor ultrawide de altísima fidelidad cromática."
  },
  {
    id: 11,
    sku: "TRS-CH-VELVET",
    name: "Silla Gamer Velvet Luxury Edition",
    category: "Sillas",
    price: 359990,
    originalPrice: 429990,
    stock: 4,
    stockCritico: 1,
    icon: "chair",
    img: "https://images.unsplash.com/photo-1598327105666-5b89351cb315?auto=format&fit=crop&w=600&q=80",
    featured: false,
    rating: 4.7,
    shortDesc: "Tapizado en terciopelo premium con herrajes dorados y base giratoria.",
    description: "La combinación perfecta entre elegancia y ergonomía avanzada."
  },
  {
    id: 12,
    sku: "TRS-LP-ULTRA",
    name: "Notebook Slim Creator 14\"",
    category: "Laptops",
    price: 999990,
    originalPrice: 1199990,
    stock: 8,
    stockCritico: 2,
    icon: "laptop",
    img: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=600&q=80",
    featured: false,
    rating: 4.6,
    shortDesc: "Solo 1.6 kg, pantalla 144Hz y hasta 8 horas de batería real.",
    description: "Ideal para creadores de contenido y gamers que viajan constantemente."
  },
  {
    id: 13,
    sku: "TRS-SP-SOUNDBAR",
    name: "Barra de Sonido RGB Bass-Boost",
    category: "Audio",
    price: 69990,
    originalPrice: 89990,
    stock: 15,
    stockCritico: 4,
    icon: "speaker",
    img: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=600&q=80",
    featured: false,
    rating: 4.6,
    shortDesc: "Sistema 2.1 con subwoofer, iluminación RGB sincronizable y control físico.",
    description: "Audio potente y limpio para tus juegos y películas favoritas debajo del monitor."
  },
  {
    id: 14,
    sku: "TRS-CP-GPU",
    name: "Tarjeta Gráfica Phantom RTX 4070",
    category: "Componentes",
    price: 789990,
    originalPrice: 899990,
    stock: 6,
    stockCritico: 2,
    icon: "gpu",
    img: "https://images.unsplash.com/photo-1591488320449-011701bb6704?auto=format&fit=crop&w=600&q=80",
    featured: true,
    rating: 4.9,
    shortDesc: "12GB GDDR6X, triple ventilador y backplate reforzado en negro y turquesa.",
    description: "Desempeño gráfico de nivel superior con DLSS 3 y arquitectura Ada Lovelace."
  },
  {
    id: 15,
    sku: "TRS-SH-HUB",
    name: "Hub Central SmartHome Control",
    category: "Hogar Inteligente",
    price: 49990,
    originalPrice: 69990,
    stock: 20,
    stockCritico: 5,
    icon: "smarthome",
    img: "https://images.unsplash.com/photo-1555680202-c86f0e12f086?auto=format&fit=crop&w=600&q=80",
    featured: false,
    rating: 4.5,
    shortDesc: "Controla luces, enchufes y cámaras desde una sola app, compatible con voz.",
    description: "Automatiza tu espacio de juego y hogar inteligente con un solo toque."
  },
  {
    id: 16,
    sku: "TRS-ST-CAM4K",
    name: "Cámara Web StreamPro 4K Ultra",
    category: "Streaming",
    price: 99990,
    originalPrice: 129990,
    stock: 12,
    stockCritico: 3,
    icon: "webcam",
    img: "https://images.unsplash.com/photo-1621259182978-fbf93132e53d?auto=format&fit=crop&w=600&q=80",
    featured: true,
    rating: 4.7,
    shortDesc: "Grabación 4K30fps, enfoque automático y corrección de luz en tiempo real.",
    description: "Transmite en alta definición con calidad de estudio para Twitch o YouTube."
  },
  {
    id: 17,
    sku: "TRS-AC-MIC",
    name: "Micrófono Condensador Studio USB",
    category: "Accesorios",
    price: 74990,
    originalPrice: 99990,
    stock: 10,
    stockCritico: 3,
    icon: "mic",
    img: "https://images.unsplash.com/photo-1598327105666-5b89351cb315?auto=format&fit=crop&w=600&q=80",
    featured: false,
    rating: 4.8,
    shortDesc: "Cápsula de condensador, patrón cardioide y silenciador táctil integrado.",
    description: "Captura tu voz con claridad cristalina y cero ruido de fondo."
  },
  {
    id: 18,
    sku: "TRS-AC-PAD",
    name: "Mousepad Extendido RGB Nebula",
    category: "Accesorios",
    price: 34990,
    originalPrice: 49990,
    stock: 25,
    stockCritico: 6,
    icon: "mousepad",
    img: "https://images.unsplash.com/photo-1616423640778-28d1b53229bd?auto=format&fit=crop&w=600&q=80",
    featured: false,
    rating: 4.6,
    shortDesc: "Superficie extendida 90x40cm con iluminación RGB perimetral y base antideslizante.",
    description: "El NEBULA RGB cubre todo tu escritorio con una superficie amplia y estable."
  }
];

let PRODUCTS = JSON.parse(localStorage.getItem('productosTecnoRosita'));
if (!PRODUCTS || PRODUCTS.length === 0) {
    PRODUCTS = PRODUCTS_DEFAULT;
    localStorage.setItem('productosTecnoRosita', JSON.stringify(PRODUCTS));
}