/* ============================================================
   TECNOROSITA — data.js
   Arreglo (Array) de productos de la tienda.
   Este arreglo es la "base de datos" en memoria del catálogo.
   Cada producto se inyecta dinámicamente en el HTML mediante
   JavaScript (ver productos.js y detalle.js).
   ============================================================ */

const PRODUCTS = [
  {
    id: 1,
    sku: "TRS-KB-APX7",
    name: "Teclado Mecánico APEX VII",
    category: "Teclados",
    price: 89990,
    originalPrice: 112990,
    stock: 14,
    stockCritico: 3,
    icon: "keyboard",
    featured: true,
    rating: 4.8,
    shortDesc: "Switches mecánicos hot-swap, retroiluminación RGB por tecla y estructura en aluminio aeronáutico.",
    description: "El APEX VII fue diseñado para jugadores que no aceptan concesiones. Su chasis de aluminio CNC ofrece una rigidez absoluta, mientras que los switches mecánicos hot-swap permiten personalizar el tacto sin soldadura. La iluminación RGB por tecla, sincronizable con toda la línea TecnoRosita, transforma tu escritorio en una experiencia inmersiva. Incluye reposamuñecas magnético de cuero vegano y cable USB-C trenzado desmontable."
  },
  {
    id: 2,
    sku: "TRS-MS-VPR2",
    name: "Mouse Inalámbrico VIPER II",
    category: "Mouse",
    price: 54990,
    originalPrice: 68990,
    stock: 22,
    stockCritico: 5,
    icon: "mouse",
    featured: true,
    rating: 4.7,
    shortDesc: "Sensor óptico 32.000 DPI, 58 g de peso y hasta 90 horas de batería.",
    description: "Precisión quirúrgica en un cuerpo ultraligero de 58 gramos. El VIPER II integra un sensor óptico de 32.000 DPI con 0 % de aceleración, switches ópticos de 90 millones de clics y conexión inalámbrica de baja latencia (1ms). Su batería de largo alcance entrega hasta 90 horas de uso continuo, ideal para maratones de torneo."
  },
  {
    id: 3,
    sku: "TRS-HS-AUR5",
    name: "Audífonos AURUM 5.1 Surround",
    category: "Audífonos",
    price: 74990,
    originalPrice: 91990,
    stock: 18,
    stockCritico: 4,
    icon: "headset",
    featured: true,
    rating: 4.9,
    shortDesc: "Sonido envolvente 5.1, micrófono con cancelación de ruido y aros de dorados.",
    description: "AURUM redefine el audio gamer premium: drivers de 50 mm con sonido envolvente virtual 5.1, micrófono retráctil con cancelación activa de ruido y almohadillas de espuma viscoelástica recubiertas en cuero. Los detalles en acabado dorado cepillado le dan una presencia de lujo sobre cualquier escritorio."
  },
  {
    id: 4,
    sku: "TRS-MN-OBS27",
    name: "Monitor OBSIDIAN 27'' 240Hz",
    category: "Monitores",
    price: 349990,
    originalPrice: 412990,
    stock: 9,
    stockCritico: 2,
    icon: "monitor",
    featured: true,
    rating: 4.9,
    shortDesc: "Panel QHD 240Hz, 1ms de respuesta y compatibilidad G-Sync / FreeSync.",
    description: "El OBSIDIAN 27'' entrega una resolución QHD (2560x1440) con una tasa de refresco de 240Hz y tiempo de respuesta de 1ms GtG, eliminando el ghosting incluso en los duelos más intensos. Su marco ultra delgado y base ajustable en altura, inclinación y giro se integran perfectamente en cualquier setup de alta gama."
  },
  {
    id: 5,
    sku: "TRS-CH-THR1",
    name: "Silla Gamer THRONE Elite",
    category: "Sillas",
    price: 279990,
    originalPrice: 358990,
    stock: 7,
    stockCritico: 2,
    icon: "chair",
    featured: false,
    rating: 4.6,
    shortDesc: "Cuero premium, reclinación 165°, soporte lumbar 4D y base de aluminio.",
    description: "THRONE Elite combina ergonomía y estatus. Tapizada en cuero sintético premium con costuras doradas, cuenta con soporte lumbar ajustable en 4 direcciones, reposabrazos 4D y reclinación de hasta 165°. Su base de aluminio soporta hasta 150 kg con total estabilidad."
  },
  {
    id: 6,
    sku: "TRS-LP-TITAN15",
    name: "Notebook Gamer TITAN 15 RTX",
    category: "Laptops",
    price: 1299990,
    originalPrice: 1533990,
    stock: 5,
    stockCritico: 1,
    icon: "laptop",
    featured: true,
    rating: 4.9,
    shortDesc: "GPU RTX serie 40, pantalla 165Hz QHD y chasis de magnesio negro mate.",
    description: "El TITAN 15 es la máquina insignia de TecnoRosita: procesador de última generación, GPU dedicada de gama alta, 32GB de RAM y pantalla QHD a 165Hz con calibración de fábrica. Su chasis de aleación de magnesio con acentos dorados resiste el uso intensivo sin sacrificar portabilidad."
  },
  {
    id: 7,
    sku: "TRS-KB-NOX60",
    name: "Teclado Compacto NOX 60%",
    category: "Teclados",
    price: 64990,
    originalPrice: 81990,
    stock: 16,
    stockCritico: 4,
    icon: "keyboard",
    featured: false,
    rating: 4.5,
    shortDesc: "Formato 60% ultra portátil, conexión tri-modo y switches silenciosos.",
    description: "Diseñado para setups minimalistas sin sacrificar rendimiento. El NOX 60% ofrece conexión tri-modo (USB-C, Bluetooth 5.0 y 2.4GHz), switches silenciosos pre-lubricados y una carcasa de policarbonato con acabado 'gasket mount' que reduce el ruido y mejora la sensación al escribir."
  },
  {
    id: 8,
    sku: "TRS-MS-GLD3",
    name: "Mouse GOLD EDITION Pro",
    category: "Mouse",
    price: 69990,
    originalPrice: 87990,
    stock: 11,
    stockCritico: 3,
    icon: "mouse",
    featured: false,
    rating: 4.7,
    shortDesc: "Edición limitada con acabados dorados y sensor de 26.000 DPI.",
    description: "Edición limitada de nuestro mouse insignia, con acabados en dorado de 18 quilates sobre carcasa negra mate. Sensor óptico de 26.000 DPI, pie de PTFE de alta duración y switches mecánicos de tacto premium para quienes buscan lujo y rendimiento en igual medida."
  },
  {
    id: 9,
    sku: "TRS-HS-ROSEPRO",
    name: "Audífonos ROSE PRO Wireless",
    category: "Audífonos",
    price: 99990,
    originalPrice: 127990,
    stock: 13,
    stockCritico: 3,
    icon: "headset",
    featured: false,
    rating: 4.8,
    shortDesc: "Inalámbricos, 40 horas de batería y drivers planares de alta fidelidad.",
    description: "Libertad total sin cables. Los ROSE PRO Wireless incorporan drivers planares de alta fidelidad, hasta 40 horas de batería y baja latencia optimizada para gaming competitivo. Su diadema acolchada y bisagras metálicas garantizan durabilidad en sesiones extensas."
  },
  {
    id: 10,
    sku: "TRS-MN-CURVE34",
    name: "Monitor Curvo CURVE 34'' UltraWide",
    category: "Monitores",
    price: 459990,
    originalPrice: 574990,
    stock: 6,
    stockCritico: 2,
    icon: "monitor",
    featured: false,
    rating: 4.8,
    shortDesc: "Panel curvo 21:9, resolución UWQHD y 165Hz para inmersión total.",
    description: "El formato ultra panorámico CURVE 34'' amplía tu campo de visión con una curvatura de 1500R, resolución UWQHD y 165Hz de refresco. Perfecto para simuladores, RPG de mundo abierto y productividad multitarea sin bordes visibles."
  },
  {
    id: 11,
    sku: "TRS-CH-VELVET",
    name: "Silla Ejecutiva Gamer VELVET Gold",
    category: "Sillas",
    price: 319990,
    originalPrice: 422990,
    stock: 4,
    stockCritico: 1,
    icon: "chair",
    featured: false,
    rating: 4.7,
    shortDesc: "Tapizado en terciopelo premium con herrajes dorados y base giratoria.",
    description: "Una fusión entre mobiliario ejecutivo y ergonomía gamer. Tapizado en terciopelo de alta densidad, herrajes cromados en acabado dorado, reposabrazos acolchados y sistema de balanceo suave. La pieza central perfecta para un setup de streaming de lujo."
  },
  {
    id: 12,
    sku: "TRS-LP-STRIKE14",
    name: "Notebook Ultraliviano STRIKE 14",
    category: "Laptops",
    price: 899990,
    originalPrice: 1151990,
    stock: 8,
    stockCritico: 2,
    icon: "laptop",
    featured: false,
    rating: 4.6,
    shortDesc: "Solo 1.6 kg, pantalla 144Hz y hasta 8 horas de batería real.",
    description: "STRIKE 14 es la opción para quienes buscan movilidad sin renunciar al rendimiento gamer. Chasis de aluminio de 1.6 kg, pantalla de 144Hz con bordes ultra delgados y una batería que rinde hasta 8 horas en uso mixto, ideal para estudiar, trabajar y jugar donde sea."
  },
  {
    id: 13,
    sku: "TRS-AU-PULSE21",
    name: "Parlantes Gamer PULSE 2.1",
    category: "Audio",
    price: 79990,
    originalPrice: 104990,
    stock: 15,
    stockCritico: 4,
    icon: "speaker",
    featured: false,
    rating: 4.6,
    shortDesc: "Sistema 2.1 con subwoofer, iluminación RGB sincronizable y control físico.",
    description: "El sistema PULSE 2.1 entrega graves profundos gracias a su subwoofer dedicado, con satélites de agudos cristalinos e iluminación RGB envolvente que se sincroniza con el resto de tu setup TecnoRosita. Incluye control de volumen físico con acabado en dorado cepillado."
  },
  {
    id: 14,
    sku: "TRS-CP-FORGE4070",
    name: "Tarjeta Gráfica RTX FORGE 4070",
    category: "Componentes",
    price: 649990,
    originalPrice: 838990,
    stock: 6,
    stockCritico: 2,
    icon: "gpu",
    featured: true,
    rating: 4.9,
    shortDesc: "12GB GDDR6X, triple ventilador y backplate reforzado en negro y turquesa.",
    description: "La RTX FORGE 4070 lleva tus fps al siguiente nivel con 12GB de memoria GDDR6X, sistema de triple ventilador de bajo ruido y un backplate de aluminio con acentos turquesa. Compatible con ray tracing en tiempo real y DLSS de última generación."
  },
  {
    id: 15,
    sku: "TRS-HM-NOVAHUB",
    name: "Hub Inteligente NOVA HOME",
    category: "Hogar Inteligente",
    price: 49990,
    originalPrice: 64990,
    stock: 20,
    stockCritico: 5,
    icon: "smarthome",
    featured: false,
    rating: 4.5,
    shortDesc: "Controla luces, enchufes y cámaras desde una sola app, compatible con voz.",
    description: "NOVA HOME centraliza el control de tu hogar inteligente: luces, enchufes, sensores y cámaras compatibles, todo desde una sola aplicación. Compatible con asistentes de voz y con modo \"Gaming Ambiente\" que sincroniza la iluminación del hogar con tu setup."
  },
  {
    id: 16,
    sku: "TRS-ST-VISION4K",
    name: "Cámara Streaming VISION 4K",
    category: "Streaming",
    price: 54990,
    originalPrice: 71990,
    stock: 12,
    stockCritico: 3,
    icon: "webcam",
    featured: true,
    rating: 4.7,
    shortDesc: "Grabación 4K30fps, enfoque automático y corrección de luz en tiempo real.",
    description: "Lleva tus transmisiones a calidad profesional con VISION 4K: grabación 4K a 30fps, enfoque automático de alta precisión y corrección de luz en tiempo real. Incluye clip ajustable y trípode compacto incluido."
  },
  {
    id: 17,
    sku: "TRS-ST-VOXAUSB",
    name: "Micrófono Streaming VOXA USB",
    category: "Streaming",
    price: 59990,
    originalPrice: 79990,
    stock: 10,
    stockCritico: 3,
    icon: "mic",
    featured: false,
    rating: 4.8,
    shortDesc: "Cápsula de condensador, patrón cardioide y silenciador táctil integrado.",
    description: "El VOXA USB entrega una captura de voz cristalina gracias a su cápsula de condensador de gran diafragma y patrón cardioide, que aísla tu voz del ruido ambiente. Incluye silenciador táctil integrado y soporte antivibración."
  },
  {
    id: 18,
    sku: "TRS-AC-NEBULAXL",
    name: "Mousepad XL NEBULA RGB",
    category: "Accesorios",
    price: 24990,
    originalPrice: 32990,
    stock: 25,
    stockCritico: 6,
    icon: "mousepad",
    featured: false,
    rating: 4.6,
    shortDesc: "Superficie extendida 90x40cm con iluminación RGB perimetral y base antideslizante.",
    description: "El NEBULA RGB cubre todo tu escritorio con una superficie extendida de 90x40cm, costuras reforzadas contra el deshilachado e iluminación RGB perimetral sincronizable. Base de goma antideslizante para máxima estabilidad en cada partida."
  }
];
