/* TECNOROSITA — validaciones.js: funciones reutilizables */
var REGEX_CORREO=/^[a-zA-Z0-9._%+-]+@(duoc\.cl|profesor\.duoc\.cl|gmail\.com)$/i;
var DOMINIOS_OK=["duoc.cl","profesor.duoc.cl","gmail.com"];
function calcularDV(c){var s=0,m=2;for(var i=c.length-1;i>=0;i--){s+=Number(c[i])*m;m=m===7?2:m+1}var r=11-(s%11);return r===11?"0":r===10?"K":String(r)}
function validarRun(v){var r=String(v||"").trim().toUpperCase();if(!r)return"El RUN es obligatorio.";if(/[.\-]/.test(r))return"Sin puntos ni guion. Ej: 123456785";if(r.length<7||r.length>9)return"Entre 7 y 9 caracteres.";if(!/^\d+[\dK]$/.test(r))return"Solo números y al final el dígito verificador (0-9 o K).";var dv=calcularDV(r.slice(0,-1));return r.slice(-1)===dv?null:"RUN no válido: para "+r.slice(0,-1)+" el dígito verificador es "+dv+"."}
function sugerirDominio(d){var dist=function(a,b){var m=[];for(var i=0;i<=a.length;i++){m[i]=[i];for(var j=1;j<=b.length;j++){m[0][j]=j;if(i>0)m[i][j]=Math.min(m[i-1][j]+1,m[i][j-1]+1,m[i-1][j-1]+(a[i-1]===b[j-1]?0:1))}}return m[a.length][b.length]};var best=null,min=3;DOMINIOS_OK.forEach(function(x){var v=dist(d.toLowerCase(),x);if(v<min){min=v;best=x}});return best}
function validarCorreoPermitido(v){var c=String(v||"").trim();if(!c)return"El correo es obligatorio.";if(c.length>100)return"Máximo 100 caracteres.";if(!c.includes("@"))return"Falta el @.";if(REGEX_CORREO.test(c))return null;var s=sugerirDominio(c.split("@")[1]||"");return s?"Dominio no permitido. ¿Quisiste decir @"+s+"?":"Solo @duoc.cl, @profesor.duoc.cl o @gmail.com."}
function validarClave(v){var s=String(v||"");if(!s)return"La contraseña es obligatoria.";if(s.length<4)return"Mínimo 4 caracteres.";if(s.length>10)return"Máximo 10 caracteres.";return null}
function validarTexto(v,o){o=o||{};var t=String(v||"").trim();var req=o.requerido!==false;if(!t)return req?(o.nombre||"Este campo")+" es obligatorio.":null;if(o.min&&t.length<o.min)return(o.nombre||"Este campo")+" debe tener al menos "+o.min+" caracteres.";if(o.max&&t.length>o.max)return(o.nombre||"Este campo")+" no puede superar "+o.max+" caracteres.";return null}
function validarNumero(v,o){o=o||{};var t=String(v??"").trim();if(!t)return o.requerido!==false?(o.nombre||"Este campo")+" es obligatorio.":null;var n=Number(t);if(isNaN(n))return"Debe ser un número.";if(o.entero&&!Number.isInteger(n))return"Solo números enteros.";if(n<(o.min||0))return"No puede ser menor a "+(o.min||0)+".";return null}
function mostrarMensaje(inp,msg){if(!inp)return!msg;var g=inp.closest(".form-group")||inp.parentElement;var sp=g.querySelector(".form-error");if(!sp){sp=document.createElement("span");sp.className="form-error";sp.setAttribute("role","alert");g.appendChild(sp)}sp.textContent=msg||"";sp.style.color="var(--danger)";sp.hidden=!msg;inp.classList.toggle("is-invalid",!!msg);inp.classList.toggle("is-valid",!msg&&inp.value!=="");return!msg}
function validarEnVivo(reglas){Object.entries(reglas).forEach(function(e){var campo=document.getElementById(e[0]);if(!campo)return;var run=function(){mostrarMensaje(campo,e[1]())};campo.addEventListener("blur",run);campo.addEventListener("change",run);campo.addEventListener("input",function(){if(campo.classList.contains("is-invalid")||campo.value.length>2)run()})});return function(){var ok=true,primero=null;Object.entries(reglas).forEach(function(e){var campo=document.getElementById(e[0]);if(campo&&!mostrarMensaje(campo,e[1]())){ok=false;primero=primero||campo}});if(primero)primero.focus();return ok}}
